- name: Install Apache2
  apt:
    name: apache2
    state: present
    update_cache: yes
  become: yes

- name: Start Apache2 and enable on boot
  systemd:
    name: apache2
    state: started
    enabled: yes
  become: yes

- name: Deploy webpage
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
    owner: www-data
    group: www-data
    mode: '0644'
  become: yes

- name: Ensure Apache2 is running
  systemd:
    name: apache2
    state: started
  become: yes